**Task - 5 Used custom exceptions TrackNotFoundException, TrackAlreadyExistsException in com.stackroute.exceptions package**
